# fly.toml app configuration file for goodnews
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goodnews'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
